# =============================================================================
# Automated Build Script: Ceres Solver (CUDA) + COLMAP
# Generated by Antigravity
# Run from an elevated (Administrator) PowerShell window
# Log will be written next to this script as build_log.txt
# =============================================================================

$LogFile    = "C:\vcpkg\build_log.txt"
$CudaPath   = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.3"
$VcpkgToolchain = "C:\vcpkg\scripts\buildsystems\vcpkg.cmake"
$CeresSource    = "C:\ceres-solver"
$CeresInstall   = "C:\ceres-install"
$ColmapSource   = "C:\colmap-src"
$ColmapInstall  = "C:\colmap-install"

function Log {
    param([string]$msg)
    $timestamp = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
    $line = "[$timestamp] $msg"
    Write-Host $line
    Add-Content -Path $LogFile -Value $line
}

function Run {
    param([string]$desc, [string]$exe, [string[]]$exeArgs, [string]$workdir = $null)
    Log ">>> $desc"
    if ($workdir) { Push-Location $workdir }
    & $exe @exeArgs
    $code = $LASTEXITCODE
    if ($workdir) { Pop-Location }
    if ($code -ne 0) {
        Log "!!! FAILED: $desc (exit code $code)"
        Log "!!! Build aborted. Check log at $LogFile"
        exit 1
    }
    Log "<<< OK: $desc"
}

# Clear old log
if (Test-Path $LogFile) { Remove-Item $LogFile }
Log "Build script started."

# Setup CUDA on PATH
$env:PATH = "$CudaPath\bin;" + $env:PATH
$env:CUDA_PATH = $CudaPath

# Load VS developer environment
$vswherePaths = @(
    "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe",
    "C:\Program Files\Microsoft Visual Studio\Installer\vswhere.exe"
)
$vswhere = $vswherePaths | Where-Object { Test-Path $_ } | Select-Object -First 1

if ($vswhere) {
    $vsPath = & $vswhere -latest -property installationPath
    Log "Visual Studio found at: $vsPath"
    $vcvars = "$vsPath\VC\Auxiliary\Build\vcvars64.bat"
    if (Test-Path $vcvars) {
        Log "Loading VS x64 environment..."
        $tempBat = [System.IO.Path]::GetTempFileName() + ".bat"
        Set-Content $tempBat "@echo off`r`ncall `"$vcvars`"`r`nset"
        $envOutput = cmd.exe /c $tempBat
        Remove-Item $tempBat -ErrorAction SilentlyContinue
        foreach ($line in $envOutput) {
            if ($line -match "^([^=]+)=(.*)$") {
                [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2], "Process")
            }
        }
        Log "VS environment loaded successfully."
    } else {
        Log "WARNING: vcvars64.bat not found."
    }
} else {
    Log "WARNING: vswhere.exe not found. VS tools may not be on PATH."
}

# Verify nvcc
Log "Verifying CUDA compiler..."
$nvccOut = & "$CudaPath\bin\nvcc.exe" --version 2>&1 | Out-String
Log $nvccOut.Trim()

# =============================================================================
# Ceres Builder (Skip if already installed)
# =============================================================================
$CeresConfigPath = "$CeresInstall\lib\cmake\Ceres\CeresConfig.cmake"
if (Test-Path $CeresConfigPath) {
    Log "Ceres Solver is already built and installed at $CeresInstall. Skipping Ceres build steps."
} else {
    # =============================================================================
    # STEP 1: Clone Ceres Solver
    # =============================================================================
    Log "===== STEP 1: Cloning Ceres Solver ====="
    if (Test-Path "$CeresSource\.git") {
        Log "Ceres source already exists, pulling latest..."
        Run "git pull ceres" "git" @("pull") $CeresSource
    } else {
        Run "git clone ceres" "git" @(
            "clone", "--depth=1",
            "https://github.com/ceres-solver/ceres-solver.git",
            $CeresSource
        )
    }

    # =============================================================================
    # STEP 2: Configure Ceres with CUDA
    # =============================================================================
    Log "===== STEP 2: Configuring Ceres with CUDA ====="
    $ceresBuild = "$CeresSource\build_cmake"
    if (-not (Test-Path $ceresBuild)) {
        New-Item -ItemType Directory -Path $ceresBuild -Force | Out-Null
    }
    if (-not (Test-Path $ceresBuild)) { Log "CRITICAL: Failed to create $ceresBuild"; exit 1 }

    Run -desc "cmake configure ceres" -exe "cmake" -exeArgs @(
        "..",
        "-G", "Visual Studio 18 2026",
        "-A", "x64",
        "-DUSE_CUDA=ON",
        "-DCMAKE_CUDA_ARCHITECTURES=75;80;86;87;88;89;90;100;103;110;120;121",
        "-DCMAKE_TOOLCHAIN_FILE=$VcpkgToolchain",
        "-DCMAKE_INSTALL_PREFIX=$CeresInstall",
        "-DCMAKE_CXX_STANDARD=17",
        "-DCMAKE_CXX_STANDARD_REQUIRED=ON",
        "-DCMAKE_CUDA_STANDARD=17",
        "-DCMAKE_CUDA_STANDARD_REQUIRED=ON",
        "-DCMAKE_CXX_FLAGS=/EHsc /Zc:preprocessor -DCCCL_IGNORE_DEPRECATED_CPP_DIALECT",
        "-DCMAKE_C_FLAGS=/Zc:preprocessor",
        "-DCMAKE_CUDA_FLAGS=-Xcompiler=/EHsc -Xcompiler=/Zc:preprocessor -DCCCL_IGNORE_MSVC_TRADITIONAL_PREPROCESSOR_WARNING -DCCCL_IGNORE_DEPRECATED_CPP_DIALECT",
        "-DBUILD_TESTING=OFF",
        "-DBUILD_EXAMPLES=OFF",
        "-DBUILD_BENCHMARKS=OFF",
        "-DMINIGLOG=OFF",
        "-DCUDA_TOOLKIT_ROOT_DIR=$CudaPath"
    ) -workdir $ceresBuild

    # =============================================================================
    # STEP 3: Build and Install Ceres
    # =============================================================================
    Log "===== STEP 3: Building Ceres (~20-40 min) ====="
    Run -desc "cmake build ceres" -exe "cmake" -exeArgs @(
        "--build", ".", "--config", "Release", "--parallel"
    ) -workdir $ceresBuild

    Run -desc "cmake install ceres" -exe "cmake" -exeArgs @(
        "--install", ".", "--config", "Release"
    ) -workdir $ceresBuild

    Log "Ceres installed to: $CeresInstall"
}

# =============================================================================
# STEP 4: Clone COLMAP
# =============================================================================
Log "===== STEP 4: Cloning COLMAP ====="
if (Test-Path "$ColmapSource\.git") {
    Log "COLMAP source already exists, resetting and pulling latest..."
    Run "git reset colmap" "git" @("reset", "--hard") $ColmapSource
    Run "git pull colmap" "git" @("pull") $ColmapSource
} else {
    Run "git clone colmap" "git" @(
        "clone", "--depth=1",
        "https://github.com/colmap/colmap.git",
        $ColmapSource
    )
}

# Patch vcpkg.json to remove duplicate Ceres dependency and add suitesparse
$vcpkgJsonPath = "$ColmapSource\vcpkg.json"
if (Test-Path $vcpkgJsonPath) {
    Log "Patching COLMAP's vcpkg.json to remove duplicate Ceres dependency and add suitesparse..."
    $json = Get-Content $vcpkgJsonPath -Raw | ConvertFrom-Json
    $newDeps = @()
    foreach ($dep in $json.dependencies) {
        if ($dep -is [string]) {
            if ($dep -ne "ceres") { $newDeps += $dep }
        } elseif ($dep -is [PSCustomObject]) {
            if ($dep.name -ne "ceres") { $newDeps += $dep }
        }
    }
    # Add suitesparse if not already present
    if ($newDeps -notcontains "suitesparse") {
        $newDeps += "suitesparse"
    }
    # Add abseil if not already present
    if ($newDeps -notcontains "abseil") {
        $newDeps += "abseil"
    }
    # Add lapack if not already present
    if ($newDeps -notcontains "lapack") {
        $newDeps += "lapack"
    }
    $json.dependencies = $newDeps

    # Add abseil override to match Ceres's abseil version
    if (-not $json.overrides) {
        $json.overrides = @()
    }
    $hasAbseilOverride = $false
    foreach ($ov in $json.overrides) {
        if ($ov.name -eq "abseil") {
            $ov.version = "20260107.1"
            $hasAbseilOverride = $true
        }
    }
    if (-not $hasAbseilOverride) {
        $json.overrides += [PSCustomObject]@{
            name = "abseil"
            version = "20260107.1"
        }
    }

    $json | ConvertTo-Json -Depth 10 | Set-Content $vcpkgJsonPath
}

# Patch SiftGPU.cpp to fix MSVC charizing operator '#@' compiler errors
$siftGpuPath = "$ColmapSource\src\thirdparty\SiftGPU\SiftGPU.cpp"
if (Test-Path $siftGpuPath) {
    Log "Patching SiftGPU.cpp to disable non-portable MSVC charizing operator..."
    $content = Get-Content $siftGpuPath -Raw
    $oldMacro = "#ifdef _MSC_VER`r`n    //charizing is microsoft only`r`n    #define MAKEINT1(a)             (#@a )`r`n#else"
    $newMacro = "#if 0 // Disabled to avoid non-portable MSVC charizing operator '#@'`r`n    //charizing is microsoft only`r`n    #define MAKEINT1(a)             (#@a )`r`n#else"
    if ($content.Contains($oldMacro)) {
        $content = $content.Replace($oldMacro, $newMacro)
        Set-Content $siftGpuPath $content -NoNewline
        Log "SiftGPU.cpp successfully patched."
    } else {
        $oldMacroLF = "#ifdef _MSC_VER`n    //charizing is microsoft only`n    #define MAKEINT1(a)             (#@a )`n#else"
        $newMacroLF = "#if 0 // Disabled to avoid non-portable MSVC charizing operator '#@'`n    //charizing is microsoft only`n    #define MAKEINT1(a)             (#@a )`n#else"
        if ($content.Contains($oldMacroLF)) {
            $content = $content.Replace($oldMacroLF, $newMacroLF)
            Set-Content $siftGpuPath $content -NoNewline
            Log "SiftGPU.cpp successfully patched (LF line endings)."
        } else {
            $pattern = "(?s)#ifdef _MSC_VER\s+//charizing is microsoft only\s+#define MAKEINT1\(a\)\s+\(#@a\s+\)\s+#else"
            if ($content -match $pattern) {
                $content = $content -replace $pattern, "#if 0 // Disabled to avoid non-portable MSVC charizing operator '#@'`r`n    //charizing is microsoft only`r`n    #define MAKEINT1(a)             (#@a )`r`n#else"
                Set-Content $siftGpuPath $content -NoNewline
                Log "SiftGPU.cpp successfully patched via regex."
            } else {
                Log "WARNING: Could not find MSVC charizing block in SiftGPU.cpp to patch."
            }
        }
    }
}


# =============================================================================
# STEP 5: Configure COLMAP
# =============================================================================
Log "===== STEP 5: Configuring COLMAP ====="
$colmapBuild = "$ColmapSource\build_cmake"
if (-not (Test-Path $colmapBuild)) {
    New-Item -ItemType Directory -Path $colmapBuild -Force | Out-Null
}
if (-not (Test-Path $colmapBuild)) { Log "CRITICAL: Failed to create $colmapBuild"; exit 1 }

$ceresCmakeDir = "$CeresInstall\lib\cmake\Ceres"
$cudssDir = "C:\Program Files\NVIDIA cuDSS\v0.8\lib\13\cmake\cudss"

Run -desc "cmake configure colmap" -exe "cmake" -exeArgs @(
    "..",
    "-G", "Visual Studio 18 2026",
    "-A", "x64",
    "-DCUDA_ENABLED=ON",
    "-DCMAKE_CUDA_ARCHITECTURES=75;80;86;87;88;89;90;100;103;110;120;121",
    "-DCMAKE_TOOLCHAIN_FILE=$VcpkgToolchain",
    "-DCMAKE_INSTALL_PREFIX=$ColmapInstall",
    "-DCMAKE_CXX_STANDARD=17",
    "-DCMAKE_CXX_STANDARD_REQUIRED=ON",
    "-DCMAKE_CUDA_STANDARD=17",
    "-DCMAKE_CUDA_STANDARD_REQUIRED=ON",
    "-DCMAKE_CXX_FLAGS=/EHsc /Zc:preprocessor -DCCCL_IGNORE_DEPRECATED_CPP_DIALECT",
    "-DCMAKE_C_FLAGS=/Zc:preprocessor",
    "-DCMAKE_CUDA_FLAGS=-Xcompiler=/EHsc -Xcompiler=/Zc:preprocessor -DCCCL_IGNORE_MSVC_TRADITIONAL_PREPROCESSOR_WARNING -DCCCL_IGNORE_DEPRECATED_CPP_DIALECT",
    "-DCeres_DIR=$ceresCmakeDir",
    "-Dcudss_DIR=$cudssDir",
    "-DCUDA_TOOLKIT_ROOT_DIR=$CudaPath",
    "-DVCPKG_BUILD_TYPE=release",
    "-DVCPKG_INSTALL_OPTIONS=--clean-after-build"
) -workdir $colmapBuild

# =============================================================================
# STEP 6: Build and Install COLMAP
# =============================================================================
Log "===== STEP 6: Building COLMAP (~30-60 min) ====="
Run -desc "cmake build colmap" -exe "cmake" -exeArgs @(
    "--build", ".", "--config", "Release", "--parallel"
) -workdir $colmapBuild

Run -desc "cmake install colmap" -exe "cmake" -exeArgs @(
    "--install", ".", "--config", "Release"
) -workdir $colmapBuild

# Copy dependency DLLs and Qt plugins to make the installation fully portable and self-contained
Log "Copying dependency DLLs and Qt plugins to $ColmapInstall\bin for portability..."
$vcpkgBin = "$ColmapSource\build_cmake\vcpkg_installed\x64-windows\bin"
$vcpkgQt6Plugins = "$ColmapSource\build_cmake\vcpkg_installed\x64-windows\Qt6\plugins"
$vcpkgQt6Bin = "$ColmapSource\build_cmake\vcpkg_installed\x64-windows\tools\Qt6\bin"

if (Test-Path $vcpkgBin) {
    Copy-Item -Path "$vcpkgBin\*.dll" -Destination "$ColmapInstall\bin\" -Force | Out-Null
}
if (Test-Path $vcpkgQt6Bin) {
    Copy-Item -Path "$vcpkgQt6Bin\*.dll" -Destination "$ColmapInstall\bin\" -Force | Out-Null
}
if (Test-Path $vcpkgQt6Plugins) {
    Copy-Item -Path "$vcpkgQt6Plugins\*" -Destination "$ColmapInstall\bin\" -Recurse -Force | Out-Null
}
$cudssBin = "C:\Program Files\NVIDIA cuDSS\v0.8\bin\13"
if (Test-Path $cudssBin) {
    Copy-Item -Path "$cudssBin\*.dll" -Destination "$ColmapInstall\bin\" -Force | Out-Null
}
Log "Dependency DLLs and Qt plugins successfully packaged."

# =============================================================================
# DONE
# =============================================================================
Log ""
Log "============================================================"
Log "  BUILD COMPLETE! Everything succeeded."
Log "  Ceres installed at : $CeresInstall"
Log "  COLMAP installed at: $ColmapInstall"
Log "  COLMAP executable  : $ColmapInstall\bin\colmap.exe"
Log "  Full log saved to  : $LogFile"
Log "============================================================"
Write-Host ""
Write-Host "Press any key to exit..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
